### ISSUE TITLE
GetItemsAsync and GetTaxonomiesAsync return "Object reference not set to an instance of an object" rather than a helpful error message, when the Project ID or ApiKey is incorrect

### ISSUE THREAD

**Issue by DeniseG001** [Kentico/kontent-delivery-sdk-net#326]
### Brief bug description

GetItemsAsync and GetTaxonomiesAsync both return {"Object reference not set to an instance of an object"} error message when the project ID or ApiKey is incorrect. This makes error handling much more difficult as it does not explain the cause.

### Repro steps

1. Create a delivery client with an invalid project id (e.g. if the project has just been re-cloned but we have forgotten to update the settings in our code)

2. Call GetTaxonomiesAsync or GetItemsAsync

e.g.    response = await deliveryClient.GetTaxonomiesAsync(new EqualsFilter("system.codename", taxonomyGroupName));

### Expected behavior

A more helpful error message, like the one below returned from GetItemAsync in the same situation:

"APIResponse returned error code: '3' APIResponse returned message: 'Missing or invalid access token. Please include the valid access token value in the Authorization header field as an HTTP bearer authorization scheme.'"

### Test environment

 - Platform: .NET Core 3.1

### Additional context

**GetItemsAsync error message and stack trace:**
  
  {"Object reference not set to an instance of an object."}   System.NullReferenceException

   Source: "Kentico.Kontent.Delivery"
   
```
   at Kentico.Kontent.Delivery.DeliveryClient.<GetItemsAsync>d__11`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Services.Content.Kentico.ItemService.AgentPortal.AgentPortalCoreKenticoClient.<GetItemsAsync>d__2`1.MoveNext() in D:\Projects\Services.Content\Data\Services.Content.Kentico\ItemService\AgentPortal\AgentPortalCoreKenticoClient.cs:line 113
```

**GetTaxonomiesAsync error message and stack trace:**

  {"Object reference not set to an instance of an object."}   System.NullReferenceException
   
   Source: "Kentico.Kontent.Delivery"
   
   StackTrace: 
   
```
   at Kentico.Kontent.Delivery.DeliveryClient.<GetTaxonomiesAsync>d__17.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Services.Content.Kentico.ItemService.AgentPortal.AgentPortalCoreKenticoClient.<GetTaxonomyGroup>d__6.MoveNext() in D:\Projects\Services.Content\Data\Services.Content.Kentico\ItemService\AgentPortal\AgentPortalCoreKenticoClient.cs:line 220
```

**Comment by MiroKentico** [comment]
Just FYI, this was released in https://github.com/Kentico/kontent-delivery-sdk-net/releases/tag/16.0.1.
